In [1]:
import torch

In [2]:
x = torch.Tensor([-4.0]).double()
x.requires_grad = True
z = 2 * x + 2 + x
q = z.relu() + z * x
h = (z * z).relu()
y = h + q + q * x
y.backward()

x, y, x.grad,

(tensor([-4.], dtype=torch.float64, requires_grad=True),
 tensor([-20.], dtype=torch.float64, grad_fn=<AddBackward0>),
 tensor([46.], dtype=torch.float64))

In [3]:
x = torch.Tensor([3.0]).double()
x.requires_grad = True
y = x ** 4

y.backward()

x, y, x.grad

(tensor([3.], dtype=torch.float64, requires_grad=True),
 tensor([81.], dtype=torch.float64, grad_fn=<PowBackward0>),
 tensor([108.], dtype=torch.float64))

In [4]:
a = torch.Tensor([-4.0]).double()
b = torch.Tensor([2.0]).double()
a.requires_grad = True
b.requires_grad = True
c = a + b
d = a * b + b**3
c = c + c + 1
c = c + 1 + c + (-a)
d = d + d * 2 + (b + a).relu()
d = d + 3 * d + (b - a).relu()
e = c - d
f = e**2
g = f / 2.0
g = g + 10.0 / f
g.backward()

a.grad, b.grad, g

(tensor([138.8338], dtype=torch.float64),
 tensor([645.5773], dtype=torch.float64),
 tensor([24.7041], dtype=torch.float64, grad_fn=<AddBackward0>))